mappings:
  CarouselSlide: DFT\SilverStripe\Carousel\Model\CarouselSlide
  CarouselPage: DFT\SilverStripe\Carousel\Extensions\CarouselPage
  ilateral\SilverStripe\Carousel\Model\CarouselSlide: DFT\SilverStripe\Carousel\Model\CarouselSlide
  ilateral\SilverStripe\Carousel\Extensions\CarouselPage: DFT\SilverStripe\Carousel\Extensions\CarouselPage
