---
Name: carouselconfig
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - ilateral\SilverStripe\Carousel\Extensions\CarouselPage
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'i-lateral/silverstripe-carousel: client/dist/scripts/carouseladmin.js'